import 'package:flutter/material.dart';

class ModelProduct {
  final String namePrdact;
  final String spuNames;
  final String photoProdact;
  final double price;
  final bool isFav;
  final String? discrbion;

  ModelProduct({
    required this.namePrdact,
    required this.spuNames,
    required this.photoProdact,
    this.price = 0,
    required this.isFav ,
    this.discrbion,
  });

  ModelProduct copyWith({
    String? namePrdact,
    String? spuNames,
    String? photoProdact,
    double? price,
    bool? isFav,
    String? discrbion,
  }) {
    return ModelProduct(
        namePrdact: namePrdact ?? this.namePrdact,
        spuNames: spuNames ?? this.spuNames,
        photoProdact: photoProdact ?? this.photoProdact,
        price: price ?? this.price,
        isFav: isFav ?? this.isFav,
        discrbion: discrbion ?? this.discrbion
    );
  }


}
List<ModelProduct> GearList = [
  ModelProduct(
    namePrdact: "PS5",
    spuNames: "Gaming Consoles",
    photoProdact: "images/Ps5.jpg",
    price: 499.99,
    isFav: false,
    discrbion: "PlayStation 5 next-gen console with fast processor and 4K support",
  ),
  ModelProduct(
    namePrdact: "Xbox X",
    spuNames: "Gaming Consoles",
    photoProdact: "images/Xboxseris.jpg",
    price: 499.99,
    isFav: false,
    discrbion: "Xbox Series X with high performance and cloud gaming support",
  ),
  ModelProduct(
    namePrdact: "Nintendo Switch",
    spuNames: "Portable Gaming",
    photoProdact: "images/HandGamis.jpg",
    price: 299.99,
    isFav: false,
    discrbion: "Nintendo Switch can be played on TV or as a portable device",
  ),
  ModelProduct(
    namePrdact: "Headset",
    spuNames: "Gaming Accessories",
    photoProdact: "images/maicro.jpg",
    price: 79.99,
    isFav: false,
    discrbion: "Gaming headset with high-quality microphone, comfortable for long use",
  ),
  ModelProduct(
    namePrdact: "Keyboard",
    spuNames: "Gaming Accessories",
    photoProdact: "images/kybord.jpg",
    price: 129.99,
    isFav: false,
    discrbion: "Mechanical gaming keyboard with RGB lighting",
  ),
  ModelProduct(
    namePrdact: "Mouse",
    spuNames: "Gaming Accessories",
    photoProdact: "images/maus.jpg",
    price: 59.99,
    isFav: false,
    discrbion: "Gaming mouse with 16000 DPI and 6 programmable buttons",
  ),
  ModelProduct(
    namePrdact: "Gaming Chair",
    spuNames: "Gaming Furniture",
    photoProdact: "images/chos.jpg",
    price: 249.99,
    isFav: false,
    discrbion: "Comfortable gaming chair with back support and armrests",
  ),
  ModelProduct(
    namePrdact: "Monitor",
    spuNames: "Gaming Monitors",
    photoProdact: "images/144z.jpg",
    price: 299.99,
    isFav: false,
    discrbion: "144Hz gaming monitor with 1ms response time",
  ),
  ModelProduct(
    namePrdact: "Gift Cards",
    spuNames: "Gift Cards",
    photoProdact: "images/Control.jpg",
    price: 50.00,
    isFav: false,
    discrbion: "50 gaming gift card for PlayStation, Xbox, or Steam",
  ),
  ModelProduct(
    namePrdact: "Controller",
    spuNames: "Gaming Accessories",
    photoProdact: "images/pasCntrol.jpg",
    price: 69.99,
    isFav: false,
    discrbion: "Wireless gaming controller with vibration feedback",
  ),
  ModelProduct(
    namePrdact: "Webcam",
    spuNames: "Streaming Accessories",
    photoProdact: "images/Camera.jpg",
    price: 89.99,
    isFav: false,
    discrbion: "1080p webcam for streaming and video calls",
  ),
  ModelProduct(
    namePrdact: "Microphone",
    spuNames: "Streaming Accessories",
    photoProdact: "images/MicrofoSmu.jpg",
    price: 99.99,
    isFav: false,
    discrbion: "Studio quality microphone for streaming and recording",
  ),
  ModelProduct(
    namePrdact: "PS4",
    spuNames: "Gaming Consoles",
    photoProdact: "images/ps4.jpg",
    price: 299.99,
    isFav: false,
    discrbion: "PlayStation 4 console with 1TB storage",
  ),
  ModelProduct(
    namePrdact: "Speakers",
    spuNames: "Audio Accessories",
    photoProdact: "images/Speker.jpg",
    price: 149.99,
    isFav: false,
    discrbion: "2.1 gaming speakers with subwoofer for immersive sound",
  ),
  ModelProduct(
    namePrdact: "Backpack",
    spuNames: "Accessories",
    photoProdact: "images/Bak.jpg",
    price: 49.99,
    isFav: false,
    discrbion: "Gaming backpack with laptop compartment and cable organizers",
  ),
];

List<ModelProduct> GamesList = [
  ModelProduct(
    namePrdact: "Cyberpunk 2077",
    spuNames: "PC, PlayStation 5",
    photoProdact: "imegGames/Cyberpunk 2077.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "An action-adventure RPG set in the dystopian future of Night City. Explore a massive open world with deep character customization, hacking abilities, and a gripping story about technology and humanity.",
  ),
  ModelProduct(
    namePrdact: "Last of Us II",
    spuNames: "PlayStation 5",
    photoProdact: "imegGames/The Last of Us Part II.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "A powerful narrative-driven game set in a post-apocalyptic world. Experience intense survival gameplay, emotional storytelling, and complex characters in this critically acclaimed sequel.",
  ),
  ModelProduct(
    namePrdact: "Halo Infinite",
    spuNames: "Xbox Series X, PC",
    photoProdact: "imegGames/Halo Infinite.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "Master Chief returns in this epic sci-fi shooter. Features an open-world environment, classic Halo combat, and a continuation of the iconic story in the Halo universe.",
  ),
  ModelProduct(
    namePrdact: "Elden Ring",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/Elden Ring.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "From the creators of Dark Souls comes this open-world fantasy RPG. Explore a vast, interconnected world filled with challenging enemies, deep lore, and rewarding exploration.",
  ),
  ModelProduct(
    namePrdact: "FIFA 24",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/FIFA24.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "The latest installment in the world's most popular football simulation. Features updated teams, enhanced graphics, new gameplay mechanics, and multiple game modes including Career and Ultimate Team.",
  ),
  ModelProduct(
    namePrdact: "God of War",
    spuNames: "PlayStation 5",
    photoProdact: "imegGames/God of War Ragnarök.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Kratos and Atreus continue their journey through Norse mythology. Features visceral combat, a compelling father-son story, and stunning visuals set across the Nine Realms.",
  ),
  ModelProduct(
    namePrdact: "Call of Duty",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/Call of Duty.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "The next chapter in the Modern Warfare series. Includes a cinematic single-player campaign, extensive multiplayer modes, and cooperative Zombies gameplay with modern graphics and mechanics.",
  ),
  ModelProduct(
    namePrdact: "Zelda",
    spuNames: "Nintendo Switch",
    photoProdact: "imegGames/The Legend of Zelda Tears of the Kingdom.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "Link returns to Hyrule in this expansive sequel to Breath of the Wild. Features new abilities, sky islands to explore, and deep physics-based puzzles in a massive open world.",
  ),
  ModelProduct(
    namePrdact: "Starfield",
    spuNames: "PC, Xbox Series X",
    photoProdact: "imegGames/Starfield.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Bethesda's first new universe in 25 years. Explore over 1,000 planets, engage in space combat, and create your own story in this epic science-fiction role-playing adventure.",
  ),
  ModelProduct(
    namePrdact: "Spider-Man 3",
    spuNames: "PlayStation 5",
    photoProdact: "imegGames/Spider-Man 3.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Swing through a detailed recreation of New York City as Spider-Man. Features enhanced web-swinging mechanics, new villains, and an expanded story with multiple playable characters.",
  ),
  ModelProduct(
    namePrdact: "Assassin's Creed",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/Assassin's Creed Mirage.jpeg",
    price: 49.99,
    isFav: false,
    discrbion: "Return to the series' roots with this stealth-focused adventure set in 9th-century Baghdad. Features parkour, assassination contracts, and a narrative-driven experience about becoming an assassin.",
  ),
  ModelProduct(
    namePrdact: "Forza Horizon 5",
    spuNames: "PC, Xbox Series X",
    photoProdact: "imegGames/Forza Horizon 5.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "Race across a beautiful open world set in Mexico. Features over 500 cars, dynamic seasons, and endless racing events in one of the most visually stunning racing games ever made.",
  ),
  ModelProduct(
    namePrdact: "Minecraft",
    spuNames: "PC, PlayStation, Xbox, Nintendo Switch",
    photoProdact: "imegGames/Minecraft.jpeg",
    price: 29.99,
    isFav: false,
    discrbion: "The ultimate sandbox building game. Explore infinite worlds, gather resources, craft tools, and build anything you can imagine in both creative and survival modes with friends.",
  ),
  ModelProduct(
    namePrdact: "GTA V",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/Grand Theft Auto V.jpeg",
    price: 39.99,
    isFav: false,
    discrbion: "Experience the massive open world of Los Santos and Blaine County. Play as three unique characters in a story of crime and ambition, or explore the continuously updated GTA Online multiplayer world.",
  ),
  ModelProduct(
    namePrdact: "Resident Evil 4",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "imegGames/Resident Evil 4 Remake.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "A complete reimagining of the classic survival horror game. Features modernized controls, stunning graphics, expanded story elements, and intense combat against terrifying enemies.",
  ),
];
List<ModelProduct> UpcomingGamesList = [
  ModelProduct(
    namePrdact: "GTA VI",
    spuNames: "PlayStation 5, Xbox Series X",
    photoProdact: "UpcGaImeg/GTAVI.jpeg",
    price: 79.99,
    isFav: false,
    discrbion: "The next chapter in the Grand Theft Auto series set in a new open-world location",
  ),
  ModelProduct(
    namePrdact: "Elder Scrolls VI",
    spuNames: "PC, Xbox Series X",
    photoProdact: "UpcGaImeg/ElderScrollsVI.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "New fantasy RPG adventure in the Elder Scrolls universe from Bethesda",
  ),
  ModelProduct(
    namePrdact: "Fable",
    spuNames: "PC, Xbox Series X",
    photoProdact: "UpcGaImeg/Fable.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "Revival of the beloved fantasy RPG series with new story and characters",
  ),
  ModelProduct(
    namePrdact: "Final Fantasy XVI",
    spuNames: "PlayStation 5",
    photoProdact: "UpcGaImeg/faill.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Latest installment in the Final Fantasy series with action-RPG combat",
  ),
  ModelProduct(
    namePrdact: "Hollow Knight",
    spuNames: "PC, PlayStation 5, Xbox Series X, Nintendo Switch",
    photoProdact: "UpcGaImeg/HollowKnight.jpeg",
    price: 39.99,
    isFav: false,
    discrbion: "Sequel to the popular metroidvania game with new areas and challenges",
  ),
  ModelProduct(
    namePrdact: "Star Wars",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "UpcGaImeg/StarWars.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "New Star Wars action-adventure game with original story and characters",
  ),
  ModelProduct(
    namePrdact: "Avowed",
    spuNames: "PC, Xbox Series X",
    photoProdact: "UpcGaImeg/Avowed.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "First-person fantasy RPG set in the Pillars of Eternity universe",
  ),
  ModelProduct(
    namePrdact: "Suicide Squad",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "UpcGaImeg/SuicideSquad.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Suicide Squad: Kill the Justice League action shooter game",
  ),
  ModelProduct(
    namePrdact: "Persona 6",
    spuNames: "PlayStation 5",
    photoProdact: "UpcGaImeg/Persona6.jpeg",
    price: 59.99,
    isFav: false,
    discrbion: "Next mainline entry in the Persona JRPG series with new cast",
  ),
  ModelProduct(
    namePrdact: "Dragon Age",
    spuNames: "PC, PlayStation 5, Xbox Series X",
    photoProdact: "UpcGaImeg/DragonAge.jpeg",
    price: 69.99,
    isFav: false,
    discrbion: "Dragon Age: Dreadwolf - New chapter in the epic fantasy RPG series",
  ),
];
List<ModelProduct>allList=[
  ...GearList,
  ... GamesList,
  ... UpcomingGamesList
];